Working basic login page, readme info with team
Lambda-School-Labs/xcel-wom-fe-b pull request #5
Opened 2021-01-07 03:01 UTC by JC8747

Changed Login title, added placeholder logo, updated contributor list… with names and github links, removed new login widget for rework.
**Team composition has changed so the readme team info will have to be updated again. **
Styling can be applied once a unified theme has been set.

2021-01-12 01:10 UTC, JoseSustaita approved these changes, later dismissed
Everything looks great, just change the readme to correctly reflect the team!

2021-01-12 01:10 UTC, JoseSustaita commented on README.md
> +|                                                      [Jose Sustaita](https://github.com/JoseSustaita)                                                       |
Since team composition has changed just update this to correctly reflect the team and it should be good to go!

2021-01-12 02:29 UTC, Cireimu requested changes
Looks good, just need you to update the team composition as well as either get rid of all the place holder images or replace them with all five team member's GitHub profile pics.

I will also need you to add a .env.sample file with the correct variables so that the CI/CD is happy and no longer blocks merge.

2021-01-14 02:15 UTC, Cireimu approved these changes

2021-01-14 02:19 UTC, JoseSustaita approved these changes
Thank you for updating the readme profile. Look good!

2021-01-14 02:19 UTC, merged